# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest
  name: Default

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - task: Docker@2
    displayName: Build image
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure for Students(1)(672a6b40-0b00-445b-9cb7-ec4553f9eb04)'
      appType: 'webAppContainer'
      WebAppName: 'StaffojiGame'
      repository: staticsite
      command: build
      Dockerfile: '**/Dockerfile'
      tags: latest
  - task: Docker@2
    displayName: Push image
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure for Students(1)(672a6b40-0b00-445b-9cb7-ec4553f9eb04)'
      appType: 'webAppContainer'
      WebAppName: 'StaffojiGame'
      repository: staticsite
      command: build
      Dockerfile: '**/Dockerfile'
      tags: latest


  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'